/**
 * Project catalogue.
 * `cover` is the index of the shot used on the card. `portrait: true` renders
 * the card media as a centred phone frame instead of a full-bleed crop.
 */
const PROJECTS = [
  {
    id: "mld",
    name: "My Local Depositor",
    tagline: "FX deposit & payout gateway for the Sri Lankan corridor",
    category: "saas",
    categoryLabel: "Payments Platform",
    year: "2026 — present",
    role: "Sole architect & engineer — product, architecture, backend, frontend, tests, deployment",
    client: "My Local Depositor — cross-border payments, Sri Lanka",
    portrait: false,
    cover: 0,
    summary:
      "A production payments platform that lets merchants collect from Sri Lankan customers in LKR and settle in USD. A merchant's system creates an order at a rate-locked quote over the API; the customer pays by bank transfer through a trilingual hosted checkout; an operator reconciles the incoming credit; confirmation posts to an immutable ledger and fires a signed webhook. Four surfaces — public API, customer checkout, operator back office and merchant/partner portals — over one domain.",
    highlights: [
      "Built and shipped the whole platform solo — <strong>domain-driven Laravel</strong> with 16 domain namespaces of final, single-purpose action classes, plus a React/Inertia back office, a Blade checkout and two self-service portals.",
      "Designed for <strong>single-writer invariants</strong>: exactly one class may write the ledger, the order state machine, the audit log and notification preferences — enforced in the models, the database and the test suite rather than in a README.",
      "Made the <strong>ledger append-only with no cached balance column anywhere</strong> — every balance is a live SUM query, and a mistake is corrected by posting a reversal, never by editing history. A counter that can silently disagree with the journal was not worth the speed.",
      "Kept money off floats end to end: NUMERIC(20,4) in Postgres, Brick\\Money in PHP, decimal <strong>strings across the wire</strong>, and a spec'd rounding direction on the LKR→USD derivation rather than an accident of the last cast.",
      "Made confirmation atomic — a single database transaction with a row lock on the order, a status-guarded no-op on double-confirm, and webhooks and mail dispatched strictly <strong>after commit</strong>.",
      "Hardened the integration surface: <strong>idempotent order creation</strong>, HMAC request signing rolled out through a dual-accept window then a hard cutover so live merchants never broke, and signed outbound webhooks with logged attempts, backoff retries and operator resend.",
      "Perf-budgeted the customer checkout for <strong>low-end Android on 4G</strong> — server-rendered Blade rather than React, reload-safe, and trilingual (English / Sinhala / Tamil) with per-script lang attributes and conditionally-loaded fonts.",
      "Wrote <strong>1,460 test cases across 155 files</strong> — roughly 30k lines of tests against 26k lines of application PHP — behind a single CI check that gates every merge.",
    ],
    stack: [
      "Laravel 13",
      "PHP 8.4",
      "PostgreSQL",
      "React 19",
      "Inertia v3",
      "TypeScript",
      "Redis / Horizon",
      "Tailwind v4",
      "Docker",
      "REST API",
    ],
    shots: [
      { src: "assets/img/mld/01-operator-dashboard.webp", caption: "Operator dashboard — cash position and per-merchant figures aggregated live from the ledger" },
      { src: "assets/img/mld/02-deposits.webp", caption: "Deposits — every order's payment lifecycle across all merchants" },
      { src: "assets/img/mld/03-ledger.webp", caption: "The append-only ledger — deposits, withdrawals and service charges, never edited" },
      { src: "assets/img/mld/04-withdrawals.webp", caption: "Withdrawal queue with service charge and derived LKR settlement amounts" },
      { src: "assets/img/mld/05-merchants.webp", caption: "Merchant management — vetting, webhook URL and balance owed" },
      { src: "assets/img/mld/06-live-rate.webp", caption: "Live FX rate — cached base rate, configured margin, staleness signal and manual override" },
      { src: "assets/img/mld/07-webhook-deliveries.webp", caption: "Signed webhook delivery log with per-attempt status, response code and resend" },
      { src: "assets/img/mld/08-audit-log.webp", caption: "Audit log — every operator decision recorded, append-only" },
      { src: "assets/img/mld/09-payout-methods.webp", caption: "Payout methods offered to merchants and partners" },
      { src: "assets/img/mld/10-payout-method-editor.webp", caption: "Payout method editor — custom destination-detail fields per method" },
      { src: "assets/img/mld/11-enquiries.webp", caption: "Enquiry tracking for web submissions and offline contacts" },
      { src: "assets/img/mld/12-merchant-dashboard.webp", caption: "Merchant portal — balance derived from the journal, not a stored counter" },
      { src: "assets/img/mld/13-merchant-deposits.webp", caption: "Merchant portal — own deposits only, hard-isolated by a global scope" },
      { src: "assets/img/mld/14-merchant-api-keys.webp", caption: "Self-service API key rotation, signing secret and hosted checkout link" },
      { src: "assets/img/mld/15-merchant-sign-in.webp", caption: "Merchant portal sign-in" },
      { src: "assets/img/mld/16-partner-wallet.webp", caption: "Partner portal — commission wallet derived by the same SUM machinery as merchant balances" },
      { src: "assets/img/mld/17-partner-merchants.webp", caption: "Partner portal — assigned merchants and per-merchant commission rates" },
      { src: "assets/img/mld/18-partner-sign-in.webp", caption: "Partner portal sign-in" },
    ],
    note: "Screenshots are from a demo environment. API keys, client IDs, checkout tokens, merchant names, payment references and webhook URLs are obscured; all monetary amounts and rates are shown as-is.",
  },
  {
    id: "linen",
    name: "Linen Studios",
    tagline: "Luxury studio booking & membership platform",
    category: "saas",
    categoryLabel: "SaaS Platform",
    year: "2022 — 2023",
    role: "Full-Stack Developer (end-to-end owner)",
    client: "Linen — portrait studio, Canada",
    portrait: false,
    cover: 0,
    summary:
      "A booking platform for a luxury portrait studio with three uniquely designed rooms. Customers book hourly slots per studio and location; staff manage shifts, pricing, memberships, points and a deep coupon rule engine from an admin dashboard.",
    highlights: [
      "Designed and built the <strong>entire application</strong> end to end — I chose the stack (Laravel API + React/MUI front end), planned delivery, and shipped to production.",
      "Built a <strong>slot generation engine</strong> that derives bookable time slots per studio from shift definitions, blocks conflicting multi-location bookings, and prices each slot live.",
      "Implemented a <strong>9-condition coupon rule engine</strong> — activation windows, usage caps, membership and user allow-lists, per-location and per-service scoping, plus override/overvalue rules that resolve against existing hourly discounts.",
      "Added <strong>membership + points</strong>: customers earn points per booking based on tier and redeem them as discounts, with tax and discount stacking resolved server-side.",
      "Shipped an admin dashboard with daily / weekly / monthly / yearly rollups and a separate customer dashboard.",
      "Integrated the payment gateway and set up version control, continuous delivery and the bug-fix workflow.",
    ],
    stack: ["Laravel", "React", "Material UI", "MySQL", "REST API", "Payment Gateway", "Git"],
    shots: [
      { src: "assets/img/linen/01-dashboard.webp", caption: "Admin dashboard — booking and revenue summary" },
      { src: "assets/img/linen/02-dashboard-analytics.webp", caption: "Dashboard analytics with period filters" },
      { src: "assets/img/linen/03-dashboard-summary.webp", caption: "Summary widgets across all modules" },
      { src: "assets/img/linen/04-shifts.webp", caption: "Shifts — time slots configured per studio" },
      { src: "assets/img/linen/05-shift-editor.webp", caption: "Shift editor with offer and actual pricing" },
      { src: "assets/img/linen/06-coupons.webp", caption: "Coupon management" },
      { src: "assets/img/linen/07-coupon-rules.webp", caption: "Coupon rule builder — scoping and override conditions" },
      { src: "assets/img/linen/08-services.webp", caption: "Services and studio configuration" },
      { src: "assets/img/linen/09-service-editor.webp", caption: "Service editor with tax and reservation rules" },
    ],
    note: "Feature detail limited by a confidentiality agreement with the client.",
  },
  {
    id: "medicentric",
    name: "Medicentric",
    tagline: "Medical services CRM — legacy rebuild",
    category: "saas",
    categoryLabel: "CRM",
    year: "2023",
    role: "Lead Developer — full rebuild",
    client: "Medicentric — medical services, USA",
    portrait: false,
    cover: 0,
    summary:
      "A US medical services company running ambulance services and insurance across multiple vendor partnerships. A legacy CRM was handed to me for a ground-up rebuild on a modern stack, with new lead, vendor and driver modules layered on top.",
    highlights: [
      "Rebuilt the legacy system on the <strong>MERN stack</strong> and dockerised it, taking measured speed from <strong>40% to 95%</strong> and downtime from <strong>30% to 1%</strong>.",
      "Made the app handle <strong>100,000 concurrent data points</strong> — the primary objective of the engagement.",
      "Built lead management end to end: lead generator, capture forms, assignment and full activity logging.",
      "Implemented <strong>zip-code territory assignment</strong> so leads route to the right vendor and driver automatically.",
      "Added bulk <strong>lead import</strong> plus a reporting and statistics layer for operations.",
      "Integrated <strong>Twilio voice calling</strong> directly into the lead workflow.",
    ],
    stack: ["MongoDB", "Express.js", "React", "Node.js", "Docker", "Twilio", "REST API"],
    shots: [
      { src: "assets/img/medicentric/01-reports.webp", caption: "Reports and statistics" },
      { src: "assets/img/medicentric/02-lead-generator.webp", caption: "Lead generator" },
      { src: "assets/img/medicentric/03-lead-form.webp", caption: "Lead capture form" },
      { src: "assets/img/medicentric/04-import-data.webp", caption: "Bulk lead import" },
      { src: "assets/img/medicentric/05-zipcode-assignment.webp", caption: "Zip-code territory assignment" },
      { src: "assets/img/medicentric/06-activities.webp", caption: "Activity log and audit trail" },
      { src: "assets/img/medicentric/07-other-reports.webp", caption: "Secondary reports" },
      { src: "assets/img/medicentric/08-create-customer.webp", caption: "Customer creation" },
      { src: "assets/img/medicentric/09-user-registration.webp", caption: "User registration and roles" },
    ],
    note: "",
  },
  {
    id: "wisermarket",
    name: "WiserMarket",
    tagline: "Brand protection platform for eCommerce",
    category: "saas",
    categoryLabel: "SaaS Platform",
    year: "2023",
    role: "React Developer, later Backend Developer",
    client: "Wiser Market — brand protection",
    portrait: false,
    cover: 0,
    summary:
      "A platform that protects brands across marketplaces. Users submit product URLs from Amazon, eBay or Walmart; the system sweeps the web for counterfeit and misuse of the product and brand name, then drives an enforcement workflow against what it finds.",
    highlights: [
      "Contracted on a <strong>3-month timeline and delivered in 2</strong> — then rehired to work on the backend.",
      "Solved the core technical challenge: a <strong>data grid with inline-editable inputs plus resizable rows and columns</strong> that stays smooth at scale, by fixing the rendering path rather than trimming features.",
      "Built the research flow — URL intake, sweep configuration, and per-match user decisions on how to handle detected misuse.",
      "Implemented column drag-and-drop reordering, layered filtering, and inline validation across the grid.",
      "Added <strong>idle detection with silent re-authorisation</strong> so long research sessions never lose work.",
      "Contributed to API development with <strong>Swagger</strong> documentation.",
    ],
    stack: ["React", "JavaScript", "Virtualised Tables", "REST API", "Swagger"],
    shots: [
      { src: "assets/img/wisermarket/01-research.webp", caption: "Research workspace" },
      { src: "assets/img/wisermarket/02-filter.webp", caption: "Grid filtering" },
      { src: "assets/img/wisermarket/03-filter-advanced.webp", caption: "Advanced multi-column filters" },
      { src: "assets/img/wisermarket/04-column-drag.webp", caption: "Drag-to-reorder columns" },
      { src: "assets/img/wisermarket/05-inline-edit.webp", caption: "Inline editable cells" },
      { src: "assets/img/wisermarket/06-validation.webp", caption: "Inline validation" },
      { src: "assets/img/wisermarket/07-choose-client.webp", caption: "Client selection" },
      { src: "assets/img/wisermarket/08-login.webp", caption: "Authentication" },
    ],
    note: "Under NDA — only three sections of the app can be shown, and no backend detail is disclosed.",
  },
  {
    id: "obexpress-admin",
    name: "OB Express — Admin",
    tagline: "Last-mile delivery operations panel",
    category: "saas",
    categoryLabel: "Logistics Admin",
    year: "2022",
    role: "Laravel Developer — admin panel + API",
    client: "OB Express — last-mile logistics, Singapore",
    portrait: false,
    cover: 0,
    summary:
      "OB Express matches delivery demand with service agents to optimise last-mile logistics, built on the founder's 35 years in the industry. I built the admin panel and the APIs consumed by the driver and customer mobile app.",
    highlights: [
      "Built the <strong>order engine</strong>: route-based price calculation, with distinct calculation rules for unique customer contracts.",
      "Implemented admin <strong>order splitting and re-creation</strong> — orders placed by contract customers are broken apart and rebuilt according to business logic before dispatch.",
      "Added driver notifications so new orders push to available agents the moment they are created.",
      "Built <strong>wallet management</strong> — admin-handled deposits and withdrawals, customer-raised requests, and a full transaction history.",
      "Shipped user management for internal staff, customers and drivers, with per-user special rates and discount rules.",
      "Wrote unit and UI tests, and owned the full lifecycle from concept through release and maintenance.",
    ],
    stack: ["Laravel", "PHP", "MySQL", "REST API", "Blade", "Git"],
    shots: [
      { src: "assets/img/obexpress-admin/01-dashboard.webp", caption: "Operations dashboard" },
      { src: "assets/img/obexpress-admin/02-dashboard-stats.webp", caption: "Dashboard statistics" },
      { src: "assets/img/obexpress-admin/03-orders.webp", caption: "Order management" },
      { src: "assets/img/obexpress-admin/04-drivers.webp", caption: "Driver management" },
      { src: "assets/img/obexpress-admin/05-transactions.webp", caption: "Wallet transactions" },
      { src: "assets/img/obexpress-admin/06-login.webp", caption: "Admin authentication" },
    ],
    note: "Feature detail limited by a confidentiality agreement with the client.",
  },
  {
    id: "obexpress-app",
    name: "OB Express — Mobile App",
    tagline: "Driver & customer delivery app",
    category: "mobile",
    categoryLabel: "Mobile App",
    year: "2022",
    role: "Mobile App Developer",
    client: "OB Express — last-mile logistics, Singapore",
    portrait: true,
    cover: 0,
    summary:
      "One app serving both sides of the OB Express marketplace. Customers book multi-stop deliveries, track them live and pay from a wallet; drivers claim available orders, navigate to each stop and withdraw their earnings — all against the Laravel API from the admin project.",
    highlights: [
      "Built a <strong>dual-role app</strong> from a single Framework7 + Vue codebase — the navigation, order list and wallet all change shape depending on whether the signed-in user is a customer or a driver.",
      "Shipped a multi-stop <strong>order builder</strong>: vehicle and service type, deliver-now or scheduled, and a reorderable pickup → stop → delivery chain that prices the route as it is assembled.",
      "Used the device <strong>GPS to build routes, drive navigation and report live position</strong>, with a Google Maps view and one-tap call to the contact at each stop.",
      "Built the <strong>wallet</strong> on both sides — customer top-up, driver withdrawal, and a per-order transaction history with statistics.",
      "Added in-app <strong>camera capture</strong> for driver document verification (licence, vehicle) and proof of delivery.",
      "Implemented <strong>local and push notifications</strong> for order assignment and status changes, and shipped early test builds so the client could stress-test on real devices — cutting the QA loop.",
    ],
    stack: ["Framework7", "Vue.js", "Google Maps & GPS", "Push Notifications", "Camera API", "REST API"],
    shots: [
      { src: "assets/img/obexpress-app/02-screen.webp", caption: "New order — vehicle, service type and multi-stop destinations" },
      { src: "assets/img/obexpress-app/09-screen.webp", caption: "Order detail — live map, stop instructions, navigate and call" },
      { src: "assets/img/obexpress-app/04-screen.webp", caption: "My orders — open, processed, completed and cancelled" },
      { src: "assets/img/obexpress-app/05-screen.webp", caption: "Customer wallet — balance, top-up and transaction history" },
      { src: "assets/img/obexpress-app/06-screen.webp", caption: "Driver wallet — earnings per order and withdrawal" },
      { src: "assets/img/obexpress-app/03-screen.webp", caption: "Customer menu — new order, orders, wallet, order import" },
      { src: "assets/img/obexpress-app/08-screen.webp", caption: "Driver menu — available orders and account verification" },
      { src: "assets/img/obexpress-app/07-screen.webp", caption: "Driver profile — licence and vehicle document upload" },
      { src: "assets/img/obexpress-app/10-notifications.webp", caption: "Push notifications" },
      { src: "assets/img/obexpress-app/01-screen.webp", caption: "Login" },
    ],
    note: "Feature detail limited by a confidentiality agreement with the client.",
  },
  {
    id: "teamguna",
    name: "Team Guna",
    tagline: "Real-estate listings platform with MLS sync",
    category: "web",
    categoryLabel: "Web Platform",
    year: "2021 — 2022",
    role: "Full-Stack Developer (end-to-end owner)",
    client: "Team Guna — real estate, Canada",
    portrait: false,
    cover: 0,
    summary:
      "A public listings site and admin platform for a Canadian real-estate team. Sold listings are managed by hand; current listings sync automatically from MLS. Buyers browse by city and on a map, and the team runs scheduled email campaigns from the same admin.",
    highlights: [
      "Built a legal <strong>MLS sync script</strong> with no usable documentation — reverse-engineered the live system from a sparse Word file, staying strictly inside their permitted framework (unauthorised scraping meant account termination and legal exposure).",
      "Delivered <strong>map-based search over 50k+ listings with sub-second lookups</strong>, seeding the map with a bounded first page and backfilling in the background so the user never waits — while keeping Google Maps API cost down.",
      "Built a <strong>custom email template builder</strong> from scratch, no packages: composable image / title / paragraph / column blocks compiled to plain HTML + CSS that renders correctly across all major clients.",
      "Added contact and email list management with categorisation, plus scheduled promotional sends to targeted groups.",
      "Shipped listing management with image upload and drag-to-reorder for the gallery slider.",
      "Built the admin dashboard with daily / weekly / monthly / yearly rollups across every module.",
    ],
    stack: ["Laravel", "React", "Material UI", "MySQL", "Google Maps API", "MLS Integration"],
    shots: [
      { src: "assets/img/teamguna/01-home.webp", caption: "Public home page" },
      { src: "assets/img/teamguna/02-home-listings.webp", caption: "Featured listings" },
      { src: "assets/img/teamguna/03-listings-toronto.webp", caption: "Listings by city" },
      { src: "assets/img/teamguna/04-listings-map.webp", caption: "Map view with listing pins" },
      { src: "assets/img/teamguna/05-admin-listings.webp", caption: "Admin — listing management" },
      { src: "assets/img/teamguna/06-admin-settings.webp", caption: "Admin — settings" },
      { src: "assets/img/teamguna/07-admin-login.webp", caption: "Admin authentication" },
    ],
    note: "Feature detail limited by a confidentiality agreement with the client.",
  },
  {
    id: "tradymac",
    name: "Tradymac",
    tagline: "Multi-category trading & services marketplace",
    category: "mobile",
    categoryLabel: "Mobile App",
    year: "2022",
    role: "Mobile App Developer",
    client: "Tradymac — marketplace",
    portrait: true,
    cover: 0,
    summary:
      "A marketplace app where traders list across six categories — agricultural produce, used goods, general products, delivery, contract workmen and rentals. Buyers surf ads, place orders, and traders manage service orders and special-buyer relationships from the same app.",
    highlights: [
      "Built the full buyer and trader experience in a single hybrid app with a tabbed shell (Ads, Favourites, Orders, My Trades).",
      "Implemented <strong>six listing categories</strong> spanning physical goods and time-based services, each with its own order shape.",
      "Built the <strong>ad creation flow</strong> and an <strong>ad surfing</strong> feed with product / service search toggling.",
      "Shipped the trader side: service order handling, contract service management and a <strong>special buyer</strong> relationship tier.",
      "Split the UI into small reusable components so the same primitives serve every category.",
    ],
    stack: ["Ionic", "TypeScript", "REST API", "Hybrid Mobile"],
    shots: [
      { src: "assets/img/tradymac/01-home.webp", caption: "Home — category grid and search" },
      { src: "assets/img/tradymac/02-ad-surfing.webp", caption: "Ad surfing feed" },
      { src: "assets/img/tradymac/03-create-ad.webp", caption: "Create ad form" },
      { src: "assets/img/tradymac/04-trader-section.webp", caption: "Trader section" },
      { src: "assets/img/tradymac/05-service-order.webp", caption: "Trader service order" },
      { src: "assets/img/tradymac/06-contract-service.webp", caption: "Contract service" },
      { src: "assets/img/tradymac/07-special-buyer.webp", caption: "Special buyer tier" },
      { src: "assets/img/tradymac/08-my-orders.webp", caption: "My orders" },
      { src: "assets/img/tradymac/09-login.webp", caption: "Login" },
    ],
    note: "",
  },
  {
    id: "dinodio",
    name: "Dinodio",
    tagline: "Parcel price comparison across DHL, FedEx & UPS",
    category: "web",
    categoryLabel: "Web Platform",
    year: "2021",
    role: "Full-Stack Developer",
    client: "Dinodio — international shipping",
    portrait: false,
    cover: 0,
    summary:
      "A shipping aggregator that quotes a parcel across DHL, FedEx and UPS in one pass and books the cheapest route — advertised savings of 50–70% versus retail carrier rates. Customers move through a multi-step quote wizard and track packages afterwards.",
    highlights: [
      "Built a <strong>multi-step quote wizard</strong> — origin and destination with residential/business classification, parcel dimensions, carrier selection, then sender and receiver details.",
      "Integrated <strong>multiple carrier rate APIs</strong> and normalised their responses into a single comparable quote list.",
      "Implemented package tracking against carrier tracking endpoints.",
      "Added multi-language support and a marketing site with blogs and contact handling.",
    ],
    stack: ["Laravel", "JavaScript", "MySQL", "Carrier APIs", "i18n"],
    shots: [
      { src: "assets/img/dinodio/01-quote-step-1.webp", caption: "Quote wizard — ship from / ship to" },
      { src: "assets/img/dinodio/02-select-carrier.webp", caption: "Carrier rate comparison" },
      { src: "assets/img/dinodio/03-sender-info.webp", caption: "Sender details" },
      { src: "assets/img/dinodio/04-contact.webp", caption: "Contact page" },
    ],
    note: "",
  },
];

const CATEGORIES = [
  { id: "all", label: "All work" },
  { id: "saas", label: "SaaS & CRM" },
  { id: "web", label: "Web platforms" },
  { id: "mobile", label: "Mobile apps" },
];
